### ISSUE TITLE
can't run with openvino r2.1

### ISSUE THREAD

**Issue by xlla** [gbr1/ros_openvino#2]
InferenceEngine API changed a lot.

**Comment by gbr1** [comment]
Hi @xlla! thank you for your issue.
I didn't know that Intel chaged Inference Engine APIs.
I'm taking a look [here](https://docs.openvinotoolkit.org/latest/_demos_object_detection_demo_ssd_async_README.html) and I think there are online few lines of code to edit and maybe the models to be compatible with newest version of OpenVINO.
I am going to work on it next days, meanwhile if you can downgrade to R1 2019, everything should be ok and working.

If you have any suggestions, please report me.

**Comment by gbr1** [comment]
readme edited: https://github.com/gbr1/ros_openvino/blob/master/README.md#--prerequisites

**Comment by gbr1** [comment]
wiki : https://github.com/gbr1/ros_openvino/wiki/Setup-environment

**Comment by gbr1** [comment]
@xlla please can you give more info about your system?
It seems to be a cross-compilation issue on aarch64

**Comment by xlla** [comment]
hi @gbr1 , thank you for those advice.
I am a newbie to openvino, and I have managed to got this project to run in raspberry pi 3.
my env:


       raspberry pi 3,
       raspbian stretch
       opencv 4.1.1-openvino
       ros melodic 1.14.3
       openvino 2019_R2  
       intel neural compute stick 2


I know there is a lot different from your setup wiki, but I don't want to use old sdk & api.
I were found those changes:
- new api use Core instead InferencePlugin to initial device.
- analysis->SetBlob will cause program segment fault, I have to byte-to-byte to feed image data.

and to improve accurate, I use cv_bridge to convert image_msg and resize it to input network size.

**Comment by gbr1** [comment]
Hi @xlla, it seems an issue about aarch64, check this [issue](https://github.com/opencv/open_model_zoo/issues/342)
If you are able, test this package on a x86 architecture.


For cv_bridge, please compile from source assuring that you are using OpenVINO compatible OpenCV.

**Comment by xlla** [comment]
yes, I am build ros components from source.

**Comment by gbr1** [comment]
hi @xlla!
I have just tested!
Everything runs perfectly on my laptop with Ubuntu 18.04 and ROS Melodic.
I'm going to simplify my wiki on setup point in next hours.

Have you solved your issue?

**Comment by gbr1** [comment]
@xlla just updated wiki: https://github.com/gbr1/ros_openvino/wiki/Fast-setup-for-Myriad-based-devices
