### ISSUE TITLE
Using nodelet for faster inference?

### ISSUE THREAD

**Issue by yandi-banyu** [gbr1/ros_openvino#4]
Hey, I'm having a difficult time understanding the working of OpenVino. If I may, I would like to requests a feature to make a nodelet version of the object_detection node. I'm building a robot that have many image processing task, so to maximize performance, I use nodelet to publish the image from camera for further processing. Is it possible to do? Or maybe give me some pointer to how it could be implemented? Thank you so much for this awesome package!

**Comment by gbr1** [comment]
Hi!
Thank you for your interest in my package!

Probably here a good point to start:
http://wiki.ros.org/nodelet

**Comment by yandi-banyu** [comment]
Alright, thanks a lot for the great pointer!
