### ISSUE TITLE
Unable to launch object_detection with Realsense D435

### ISSUE THREAD

**Issue by QixiangMa** [gbr1/ros_openvino#7]
Thank you for this detailed tutorial. Your code is a good reference for me, but I have an error while running your demo myriad_demo_realsense.launch.
I setup the development environment according to your tutorial.
My environment:
**I am using my own laptop** with Ubuntu 16.04 ROS Kinetic
Realsense D435
RealSense ROS v2.2.16
LibRealSense v2.37.0
OpenVINO 2019 R3
depth stream width: 640, height: 480, fps: 30, Format: Z16
color stream  width: 640, height: 480, fps: 30, Format: RGB8

Issue:

[object_detection-4] process has died [pid 4751, exit code 255, cmd /home/agv/catkin_ws/devel/lib/ros_openvino/object_detection /object_detection/input_image:=/camera/color/image_raw /object_detection/input_depth:=/camera/aligned_depth_to_color/image_raw /object_detection/camera_info:=/camera/aligned_depth_to_color/camera_info __name:=object_detection __log:=/home/agv/.ros/log/ad10953a-eb81-11ea-896d-acd1b8383ba1/object_detection-4.log].
log file: /home/agv/.ros/log/ad10953a-eb81-11ea-896d-acd1b8383ba1/object_detection-4*.log

Pointcloud is visible in rviz

I tried to solve the error according to the other two issues, but to no avail.

Best regards,
Qixiang

**Comment by gbr1** [comment]
Hi Qixiang,
does OpenVINO works on your laptop using a Myriad based device? This package doesn't support CPU at the moment.
If yes, probably you need to reboot because the Myriad device was initialized uncorrectly.

**Comment by QixiangMa** [comment]
> Hi Qixiang,
> does OpenVINO works on your laptop using a Myriad based device? This package doesn't support CPU at the moment.
> If yes, probably you need to reboot because the Myriad device was initialized uncorrectly.

thank you for your reply
I change the launch file
`  <param name="target"            value="GPU" />`
But it still didn't work.

**Comment by gbr1** [comment]
Can you check if D435 topics are under /camera namespace and if are correctly published?
Can you check by using a webcam and [this](https://github.com/gbr1/ros_openvino/blob/master/launch/gpu_demo_webcam.launch) launch file?

**Comment by gbr1** [comment]
Is your GPU supported by OpenVINO?

**Comment by QixiangMa** [comment]
> Is your GPU supported by OpenVINO?

I found that
_Intel® GPU is not detected on this machine
Installation can continue; however, GPU optimization will not be available for the product._
Is this a problem?

**Comment by gbr1** [comment]
Yes, it wouldn't work on your GPU.

Check if our CPU/GPU is listed:
https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/system-requirements.html

**Comment by QixiangMa** [comment]
> Yes, it wouldn't work on your GPU.
> 
> Check if our CPU/GPU is listed:
> https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/system-requirements.html

yeah, my GPU is the problem.
Anyway, thank you, I will close this issue.
